obor_codes = {
    "16": "alergologie a klinická imunologie",
    "107": "algeziologie",
    "17": "anesteziologie a intenzivní medicína",
    "1": "angiologie",
    "19": "biomedicínská kybernetika",
    "20": "cévní chirurgie",
    "21": "čelistní ortopedie",
    "22": "dermatovenerologie",
    "29": "dětská a dorostová psychiatrie",
    "23": "dětská dermatovenerologie",
    "111": "dětská endokrinologie a diabetologie",
    "2": "dětská gastroenterologie a hepatologie",
    "24": "dětská gynekologie",
    "25": "dětská chirurgie",
    "26": "dětská kardiologie",
    "3": "dětská nefrologie",
    "27": "dětská neurologie",
    "4": "dětská onkologie a hematologie",
    "28": "dětská otorinolaryngologie",
    "5": "dětská pneumologie",
    "6": "dětská radiologie",
    "7": "dětská revmatologie",
    "30": "dětská stomatologie",
    "31": "dětská urologie",
    "99": "dětské lékařství",
    "32": "diabetologie",
    "33": "dorostové lékařství",
    "34": "endokrinologie",
    "101": "endokrinologie a diabetologie",
    "35": "epidemiologie",
    "18": "foniatrie",
    "37": "gastroenterologie",
    "38": "geriatrie",
    "39": "gerontopsychiatrie",
    "40": "gynekologie a porodnictví",
    "117": "gynekologie dětí a dospívajících",
    "41": "hematolologie a transfuzní lékařství",
    "78": "hrudní chirurgie",
    "42": "hygiena a epidemiologie",
    "43": "hygiena dětí a dorostu",
    "45": "hygiena obecná a komunální",
    "46": "hygiena výživy a předmětů běžného užívání",
    "47": "hygiena záření",
    "8": "hyperbarická a letecká medicína",
    "48": "chirurgie",
    "80": "infekční lékařství",
    "9": "intenzivní medicína",
    "119": "intervenční kardiologie",
    "10": "intervenční radiologie",
    "50": "kardiochirurgie",
    "51": "kardiologie",
    "52": "klinická biochemie",
    "53": "klinická farmakologie",
    "54": "klinická onkologie",
    "102": "klinická osteologie",
    "108": "klinická výživa a intenzivní metabolická péče",
    "109": "koloproktologie",
    "55": "korektivní dermatologie",
    "57": "lékařská bakteriologie",
    "58": "lékařská genetika",
    "59": "lékařská mikrobiologie",
    "60": "lékařská parazitologie",
    "61": "lékařská virologie",
    "62": "letecké lékařství",
    "88": "maxilofaciální chirurgie",
    "103": "medicína dlouhodobé péče",
    "63": "mikrobiologie",
    "64": "mikrobiologie životního prostředí",
    "56": "návykové nemoci",
    "65": "nefrologie",
    "66": "neonatologie",
    "67": "neurochirugie",
    "68": "neurologie",
    "11": "neuroradiologie",
    "69": "nukleární medicína",
    "70": "oftalmologie",
    "104": "onkogynekologie",
    "110": "onkochirurgie",
    "112": "onkourologie",
    "71": "ortopedická protetika",
    "72": "ortopedie a traumatologie pohybového ústrojí",
    "73": "otorinolaryngologie a chirurgie hlavy a krku",
    "12": "paliativní medicína",
    "74": "parodontologie",
    "75": "patologie",
    "98": "pediatrie",
    "76": "perinatologie",
    "105": "perinatologie a fetomaternální medicína",
    "77": "plastická chirurgie",
    "93": "pneumologie a ftizeologie",
    "13": "popáleninová medicína",
    "79": "posudkové lékařství",
    "44": "pracovní lékařství",
    "100": "praktické lékařství pro děti a dorost",
    "81": "psychiatrie",
    "114": "psychosomatika",
    "83": "radiační onkologie",
    "82": "radiologie a zobrazovací metody",
    "36": "rehabilitační a fyzikální medicína",
    "14": "reprodukční medicína",
    "84": "revmatologie",
    "85": "sexuologie",
    "87": "soudní lékařství",
    "115": "spondylochirurgie",
    "89": "stomatologická protetika",
    "90": "stomatologie",
    "91": "tělovýchovné lékařství",
    "92": "traumatologie",
    "94": "tuberkulóza a respirační nemoci v dětském věku",
    "118": "úrazová chirurgie",
    "95": "urgentní medicína",
    "106": "urogynekologie",
    "96": "urologie",
    "116": "vaskulární intervenční radiologie",
    "86": "veřejné zdravotnictví",
    "49": "vnitřní lékařství",
    "97": "všeobecné praktické lékařství",
}
okres_codes = {
    "3201": "Benešov",
    "3202": "Beroun",
    "3701": "Blansko",
    "3702": "Brno-město",
    "3703": "Brno-venkov",
    "3801": "Bruntál",
    "3704": "Břeclav",
    "3501": "Česká Lípa",
    "3301": "České Budějovice",
    "3302": "Český Krumlov",
    "3502": "Děčín",
    "3401": "Domažlice",
    "3802": "Frýdek-Místek",
    "3601": "Havlíčkův Brod",
    "3706": "Hodonín",
    "3602": "Hradec Králové",
    "3402": "Cheb",
    "3503": "Chomutov",
    "3603": "Chrudim",
    "3504": "Jablonec nad Nisou",
    "3811": "Jeseník",
    "3604": "Jičín",
    "3707": "Jihlava",
    "3303": "Jindřichův Hradec",
    "3403": "Karlovy Vary",
    "3803": "Karviná",
    "3203": "Kladno",
    "3404": "Klatovy",
    "3204": "Kolín",
    "3708": "Kroměříž",
    "3205": "Kutná Hora",
    "3505": "Liberec",
    "3506": "Litoměřice",
    "3507": "Louny",
    "3206": "Mělník",
    "3207": "Mladá Boleslav",
    "3508": "Most",
    "3605": "Náchod",
    "3804": "Nový Jičín",
    "3208": "Nymburk",
    "3805": "Olomouc",
    "3806": "Opava",
    "3807": "Ostrava-město",
    "3606": "Pardubice",
    "3304": "Pelhřimov",
    "3305": "Písek",
    "3406": "Plzeň-jih",
    "3405": "Plzeň-město",
    "3407": "Plzeň-sever",
    "3100": "Praha hl.m.",
    "3209": "Praha-východ",
    "3210": "Praha-západ",
    "3306": "Prachatice",
    "3709": "Prostějov",
    "3808": "Přerov",
    "3211": "Příbram",
    "3212": "Rakovník",
    "3408": "Rokycany",
    "3607": "Rychnov nad Kněžnou",
    "3608": "Semily",
    "3409": "Sokolov",
    "3307": "Strakonice",
    "3609": "Svitavy",
    "3809": "Šumperk",
    "3308": "Tábor",
    "3410": "Tachov",
    "3509": "Teplice",
    "3610": "Trutnov",
    "3710": "Třebíč",
    "3711": "Uherské Hradiště",
    "3510": "Ústí nad Labem",
    "3611": "Ústí nad Orlicí",
    "3810": "Vsetín",
    "3712": "Vyškov",
    "3705": "Zlín",
    "3713": "Znojmo",
    "3714": "Žďár nad Sázavou",
}
